<?
include_once($_SERVER['DOCUMENT_ROOT']."/scripts/mysql.php");
$ididiomarecibido = $_REQUEST["elididioma"];

function limpia($cadena) {
	$no_permitidas= array ("'");
	$permitidas= array ("''");
	$texto = str_replace($no_permitidas, $permitidas ,$cadena);
	return $texto;
} 

$porpersona = $_REQUEST["porpersona"];
$conteo = $_REQUEST["aerolinea"];
$aerolinea = limpia($_REQUEST["aerolinea"]);
$privacidad =  limpia($_REQUEST["privacidad"]);
$ayuda =  limpia($_REQUEST["ayuda"]);
$aventura =  limpia($_REQUEST["aventura"]);
$origen =  limpia($_REQUEST["origen"]);
$comentarios =  limpia($_REQUEST["comentarios"]);
$correo =  limpia($_REQUEST["correo"]);
$cuadruple =  limpia($_REQUEST["cuadruple"]);
$descripcion =  limpia($_REQUEST["descripcion"]);
$desde =  limpia($_REQUEST["desde"]);
$dias =  limpia($_REQUEST["dias"]);
$doble =  limpia($_REQUEST["doble"]);
$enviar =  limpia($_REQUEST["enviar"]);
$escoge =  limpia($_REQUEST["escoge"]);
$estadia =  limpia($_REQUEST["estadia"]);
$ayudarte =  limpia($_REQUEST["ayudarte"]);
$faqs =  limpia($_REQUEST["faqs"]);
$fechatour =  limpia($_REQUEST["fechatour"]);
$salida =  limpia($_REQUEST["salida"]);
$llegada =  limpia($_REQUEST["llegada"]);
$habitacion =  limpia($_REQUEST["habitacion"]);
$hotel =  limpia($_REQUEST["hotel"]);
$llegadab =  limpia($_REQUEST["llegadab"]);
$hotelseleccionado =  limpia($_REQUEST["hotelseleccionado"]);
$idioma =  limpia($_REQUEST["idioma"]);
$importe =  limpia($_REQUEST["importe"]);
$impuestos =  limpia($_REQUEST["impuestos"]);
$lada =  limpia($_REQUEST["lada"]);
$llegadac =  limpia($_REQUEST["llegadac"]);
$masinfo =  limpia($_REQUEST["masinfo"]);
$menores =  limpia($_REQUEST["menores"]);
$menores =  limpia($_REQUEST["menores"]);
$menu =  limpia($_REQUEST["menu"]);
$moneda =  limpia($_REQUEST["moneda"]);
$noches =  limpia($_REQUEST["noches"]);
$nombre =  limpia($_REQUEST["nombre"]);
$novuelo =  limpia($_REQUEST["novuelo"]);
$otrostours =  limpia($_REQUEST["otrostours"]);
$paqueteseleccionado =  limpia($_REQUEST["paqueteseleccionado"]);
$paquetessimilares =  limpia($_REQUEST["paquetesimilares"]);
$cancelacion =  limpia($_REQUEST["cancelacion"]);
$preciomenor =  limpia($_REQUEST["preciomenor"]);
$preparemos =  limpia($_REQUEST["preparemos"]);
$reservaahora =  limpia($_REQUEST["reservaahora"]);
$recomendaciones =  limpia($_REQUEST["recomendaciones"]);
$salidab =  limpia($_REQUEST["salidab"]); 

$fechapaquete =  limpia($_REQUEST["fechapaquete"]);
$sencilla =  limpia($_REQUEST["sencilla"]);
$servicio =  limpia($_REQUEST["servicio"]);
$social =  limpia($_REQUEST["social"]);
$tarifaporadulto =  limpia($_REQUEST["tarifaporadulto"]);
$telefono =  limpia($_REQUEST["telefono"]);
$tipodehabitacion =  limpia($_REQUEST["tipohabitacion"]);
$triple =  limpia($_REQUEST["triple"]);
$transportacion =  limpia($_REQUEST["transportacion"]);
$letra =  limpia($_REQUEST["letra"]);
$adultos =  limpia($_REQUEST["adultos"]);
$contacto =  limpia($_REQUEST["contacto"]);
$ctos = count($conteo) - 1;

for($i=0; $i <= $ctos; $i++){
	$ididioma = $ididiomarecibido[$i];
 	$qrydelete = "delete from diccionario_descripciones where ididioma = '$ididioma'";
	ejecuta($qrydelete);
	
	$qrya="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('1', '$ididioma', '".$aerolinea[$i]."')";
	$qryb="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('2', '$ididioma', '".$privacidad[$i]."')";
	$qryc="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('3', '$ididioma', '".$ayuda[$i]."')";
	$qryd="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('4', '$ididioma', '".$aventura[$i]."')";
	$qrye="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('5', '$ididioma', '".$origen[$i]."')";
	$qryf="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('6', '$ididioma', '".$comentarios[$i]."')";
	$qryg="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('7', '$ididioma', '".$correo[$i]."')";
	$qryh="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('8', '$ididioma', '".$cuadruple[$i]."')";
	$qryi="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('9', '$ididioma', '".$descripcion[$i]."')";
	$qryj="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('10', '$ididioma', '".$desde[$i]."')";
	$qryk="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('11', '$ididioma', '".$dias[$i]."')";
	$qryl="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('12', '$ididioma', '".$doble[$i]."')";
	$qrym="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('13', '$ididioma', '".$enviar[$i]."')";
	$qryn="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('14', '$ididioma', '".$escoge[$i]."')";
	$qryo="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('15', '$ididioma', '".$estadia[$i]."')";
	$qryp="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('16', '$ididioma', '".$ayudarte[$i]."')";
	$qryq="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('17', '$ididioma', '".$faqs[$i]."')";
	$qryq22="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('58', '$ididioma', '".$fechatour[$i]."')";
	$qryr="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('18', '$ididioma', '".$salida[$i]."')";
	$qrys="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('19', '$ididioma', '".$llegada[$i]."')";	
	$qryt="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('20', '$ididioma', '".$habitacion[$i]."')";
	$qryu="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('21', '$ididioma', '".$hotel[$i]."')";
	$qryv="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('22', '$ididioma', '".$llegadab[$i]."')";
	$qryw="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('53', '$ididioma', '".$hotelseleccionado[$i]."')";
	$qryx="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('23', '$ididioma', '".$idioma[$i]."')";
	$qryy="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('24', '$ididioma', '".$importe[$i]."')";
	$qryz="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('25', '$ididioma', '".$impuestos[$i]."')";
	$qryaa="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('26', '$ididioma', '".$lada[$i]."')";
	$qrybb="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('27', '$ididioma', '".$llegadac[$i]."')";
	$qrycc="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('28', '$ididioma', '".$menores[$i]."')";
	$qrydd="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('29', '$ididioma', '".$menu[$i]."')";
	$qryee="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('30', '$ididioma', '".$moneda[$i]."')";
	$qryff="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('31', '$ididioma', '".$noches[$i]."')";
	$qrygg="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('32', '$ididioma', '".$nombre[$i]."')";
	$qryhh="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('33', '$ididioma', '".$novuelo[$i]."')";
	$qryii="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('34', '$ididioma', '".$otrostours[$i]."')";
	$qryjj="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('35', '$ididioma', '".$paqueteseleccionado[$i]."')";
	$qrykk="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('36', '$ididioma', '".$paquetessimilares[$i]."')";
	$qryll="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('37', '$ididioma', '".$cancelacion[$i]."')";
	$qrymm="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('38', '$ididioma', '".$preciomenor[$i]."')";
	$qrynn="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('39', '$ididioma', '".$preparemos[$i]."')";
	$qryoo="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('40', '$ididioma', '".$reservaahora[$i]."')";
	$qrypp="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('41', '$ididioma', '".$recomendaciones[$i]."')";
	$qryqq="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('42', '$ididioma', '".$salidab[$i]."')";	
	$qryrr="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('43', '$ididioma', '".$fechapaquete[$i]."')";
	$qryss="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('44', '$ididioma', '".$sencilla[$i]."')";		
	$qrytt="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('45', '$ididioma', '".$servicio[$i]."')";
	$qryuu="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('46', '$ididioma', '".$social[$i]."')";
	$qryvv="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('47', '$ididioma', '".$tarifaporadulto[$i]."')";
	$qryww="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('48', '$ididioma', '".$telefono[$i]."')";
	$qryxx="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('49', '$ididioma', '".$tipodehabitacion[$i]."')";
	$qryyy="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('50', '$ididioma', '".$triple[$i]."')";
	$qryzz="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('51', '$ididioma', '".$transportacion[$i]."')";
	$qryaaa="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('52', '$ididioma', '".$letra[$i]."')";	
	$qryaab="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('54', '$ididioma', '".$adultos[$i]."')";
	$qryaac="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('55', '$ididioma', '".$contacto[$i]."')";
	$qryaad="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('56', '$ididioma', '".$masinfo[$i]."')";
	$qryaae="insert into diccionario_descripciones (idpalabra, ididioma, traduccion) values ('59', '$ididioma', '".$porpersona[$i]."')";	
	

	ejecuta($qrya);
	ejecuta($qryb);
	ejecuta($qryc);
	ejecuta($qryd);
	ejecuta($qrye);
	ejecuta($qryf);	
	ejecuta($qryg);
	ejecuta($qryh);
	ejecuta($qryi);
	ejecuta($qryj);
	ejecuta($qryk);
	ejecuta($qryl);	
	ejecuta($qrym);
	ejecuta($qryn);
	ejecuta($qryo);
	ejecuta($qryp);
	ejecuta($qryq);
	ejecuta($qryr);
	ejecuta($qrys);
	ejecuta($qryt);
	ejecuta($qryu);
	ejecuta($qryv);
	ejecuta($qryw);
	ejecuta($qryx);	
	ejecuta($qryy);
	ejecuta($qryz);
	ejecuta($qryaa);
	ejecuta($qrybb);
	ejecuta($qrycc);
	ejecuta($qrydd);	
	ejecuta($qryee);
	ejecuta($qryff);
	ejecuta($qrygg);
	ejecuta($qryhh);
	ejecuta($qryii);
	ejecuta($qryjj);	
	ejecuta($qrykk);
	ejecuta($qryll);
	ejecuta($qrymm);
	ejecuta($qrynn);
	ejecuta($qryoo);
	ejecuta($qrypp);	
	ejecuta($qryqq);
	ejecuta($qryrr);
	ejecuta($qryss);
	ejecuta($qrytt);
	ejecuta($qryuu);
	ejecuta($qryvv);	
	ejecuta($qryww);
	ejecuta($qryxx);
	ejecuta($qryyy);
	ejecuta($qryzz);
	ejecuta($qryaaa);
	ejecuta($qryaab);	
	ejecuta($qryaac);
	ejecuta($qryaad);
	ejecuta($qryq22);
	ejecuta($qryaae);
	
							
}

?>
